info:
  url: https://github.com/spencergibb/myfeed

gh84:
  test: '{cipher}fedcbf7b7eb206f84c29baa205a4090546c2b7b59523076958a5ea5d8eddd116'

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery.myfeed.com:11010/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
