info:
  url: https://github.com/spencergibb/myfeed

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery.myfeed.com:11010/eureka/